### PR TITLE
Changes from production branch

### PR DESCRIPTION
**Pull request by outoftime**
A few commits are on the production branch but not upstream. These are them.

### CODE REVIEW

**Comment by outoftime** [comment]
Just bringing up to date, no review

**Comment by a-warner** [comment]
yikes, must've forgot to push those

**Comment by a-warner** [comment]
actually i think they're on a branch locally that i was testing out...either way not great

**Comment by a-warner** [comment]
heres the branch: https://github.com/a-warner/knowledgebot/tree/slack_integration

**Comment by outoftime** [comment]
@a-warner cool, will merge that branch into downstream for accounting purposes

**Pull request merged**
